### ISSUE TITLE
Rethinking the ekotrace analysis CLI

### ISSUE THREAD

**Issue by pittma** [auxoncorp/ekotrace#114]
## Overview
Rather than having `analysis` as a subcommand, Ekotrace should have an `export` subcommand:

```
ekotrace export <input_file.ekt>  [--type=cyclic | --type=acyclic default:acyclic] --locations=something.csv --events=other.csv [-o,--output <output_file> default: out.<format>] [--segments-only] [--format=dot,gexf,gml default: dot]
```

This subcommand produces 4 different representations of the causal history given by `input_file`, and those are selected by the arguments given via the `--type` switch, and whether or not `--segments-only` is used.

&nbsp; | Cyclic | Acyclic 
-|-|-
**With `--segments-only`** | A topology graph, with edges between tracers weighted by occurrence. | The causal history on a segment-by-segment basis. |
**Without  `--segments-only`** | A state graph, with edges between event types weighted by occurrence. | The complete causal history, event-by-event. |

These graphs will include the metadata for the events and the tracers in a form that is amenable to tools like Gephi. For `dot` output types, for instance, this information will go in the `attrs` section of nodes and edges.

While the CLI documented above states that there will be more than one format available, for the initial implementation, we'll stick to just dot.

## Changes

1. The `analysis` subcommand is replaced with this new export command.

## Implementation details

In order to legibly "address" the vertices in our dot files, we need to use metadata we have available, but are prevented from doing this directly in Petgraph, as it identifies vertices with their `NodeIndex`s. Instead, the graph building code shall use the same API (`add_node` / `add_edge`) to construct simple vertex and edge lists, this way, we can be parametric over which graph library is being used by the code that ingests the streamed, unordered columnar (CSV at the time of writing) data and converts it into a graph, leaving it possible to have the data in a Petgraph graph should we wish to make use of its analysis.

The other area we may wish to be parametric is the incoming data source. This would allow for the raw-data-set-to-graph-form code to be reusable with any backend storage, so long as it may be treated as a stream (or very long) list of `Event`s.

**Comment by nathanaschbacher** [comment]
Thinking about this a bit I understand a Segment to be:

> "The events between clock ticks."

So, when we say `--only-segments` , and if segments are, "The events between clock ticks", then I might expect `--only-segments` to show me... "The events between clock ticks.", but it actually does something different. It only shows you the clock ticks (sort of), not the events between them.

Maybe this is something more like `--without-events` or `--tracers-only` or `--locations-only` or whatever language makes sense?
